export const STUDY_SOURCE = "https://download.inep.gov.br/publicacoes/institucionais/avaliacoes_e_exames_da_educacao_basica/a_redacao_no_enem_2025_cartilha_do_participante.pdf";

export const ESSAY_CHAPTERS = [
  { title: "Entenda a dissertação argumentativa", summary: "Defenda uma posição com razões explicadas e uma proposta de intervenção.", lesson: "O tema define o problema; a tese apresenta sua posição; os argumentos explicam por que ela se sustenta. Narrar um caso pode contextualizar, mas o objetivo principal é analisar uma questão social. Cada parágrafo precisa acrescentar uma etapa ao raciocínio.", example: "Tema: inclusão digital de idosos. Tese: a falta de formação acessível e de interfaces inclusivas dificulta a autonomia dessa população. Os dois problemas anunciados organizam o desenvolvimento.", exercise: "Escreva uma tese de uma frase. Circule os dois problemas que você consegue explicar sem repetir ideias.", check: "Minha tese responde ao recorte inteiro, em vez de comentar apenas o assunto geral?" },
  { title: "Leia o tema e delimite o recorte", summary: "Transforme as palavras da proposta em limites para o seu texto.", lesson: "Separe assunto, problema, grupo afetado e contexto. Leia os textos motivadores para reconhecer perspectivas; não os copie como se fossem argumento próprio. Diferencie causa, consequência e solução antes de começar a escrever.", example: "Inclusão digital é o assunto; barreiras de acesso são o problema; idosos são o grupo; Brasil é o contexto. Um texto só sobre os benefícios da internet deixaria de enfrentar as barreiras desse grupo.", exercise: "Faça quatro caixas: assunto, problema, grupo e contexto. Preencha cada uma e escreva uma pergunta que sua redação responderá.", check: "Os dois argumentos mantêm o grupo e o problema pedidos?" },
  { title: "Planeje com um mapa mental", summary: "Conecte diagnóstico e solução antes de escrever os parágrafos.", lesson: "Coloque o recorte no centro. Abra dois ramos de causas e, em cada um, conecte uma consequência, uma referência e uma ação possível. Uma referência só deve entrar se ajudar a explicar aquela causa. O mapa é um planejamento, não uma lista de palavras para encaixar à força.", example: "Inclusão digital → formação insuficiente → dificuldade de usar serviços → educação para autonomia → oficinas em bibliotecas. Segundo ramo: interfaces inacessíveis → dependência de terceiros → direito à participação → testes de acessibilidade.", exercise: "Reproduza o mapa abaixo com um tema do Laboratório. Elimine qualquer ramo que não chegue a uma consequência concreta.", check: "A intervenção resolve os problemas que aparecem nos ramos?" },
  { title: "Construa a introdução", summary: "Contextualize, apresente o problema e anuncie a tese.", lesson: "A contextualização deve abrir caminho para o recorte. Em seguida, mostre a tensão que será analisada e apresente sua posição. Você pode começar por uma observação histórica, uma obra ou uma situação social; não é obrigatório abrir com citação.", example: "A digitalização ampliou o acesso remoto a serviços. Entretanto, parte da população idosa enfrenta barreiras para utilizá-los de modo autônomo. Nesse cenário, a formação insuficiente e o desenho pouco acessível das plataformas dificultam a inclusão.", exercise: "Escreva uma introdução de três frases e identifique a função de cada uma.", check: "A contextualização se conecta à tese sem um salto de assunto?" },
  { title: "Desenvolva o primeiro argumento", summary: "Afirmação → explicação → evidência → análise → fechamento.", lesson: "O tópico frasal apresenta uma ideia defensável. Explique o mecanismo: como a causa produz a consequência? Acrescente repertório e interprete sua contribuição. Feche retomando o efeito para o tema. Dizer que um problema é grave sem explicar por quê não desenvolve um argumento.", example: "A falta de formação limita a autonomia digital. Sem orientação para reconhecer interfaces e riscos, idosos podem depender de terceiros para acessar serviços. A noção de autonomia educacional discutida por Paulo Freire ajuda a compreender por que ensinar procedimentos deve incluir participação e compreensão, e não simples repetição.", exercise: "Depois de cada afirmação, acrescente uma resposta a ‘como isso acontece?’. Corte afirmações que permaneçam sem explicação.", check: "Expliquei a ligação entre referência e problema?" },
  { title: "Progrida no segundo argumento", summary: "Acrescente uma causa distinta e conecte-a à tese.", lesson: "O segundo desenvolvimento não deve apenas trocar as palavras do primeiro. Se o primeiro trata de formação, o segundo pode examinar barreiras de acessibilidade. Relacione os parágrafos: mesmo uma pessoa treinada pode enfrentar um sistema mal projetado. Essa conexão dá progressão ao texto.", example: "Além da formação, o desenho das plataformas interfere no acesso. Letras pequenas e caminhos confusos dificultam a navegação. Assim, responsabilizar apenas o usuário oculta escolhas de projeto que também precisam mudar.", exercise: "Resuma os dois parágrafos em títulos. Se os títulos forem equivalentes, substitua um eixo.", check: "O segundo argumento acrescenta uma explicação relevante?" },
  { title: "Use repertório de forma produtiva", summary: "Identifique a fonte, explique a ideia e aplique-a ao argumento.", lesson: "Diferencie citação literal de paráfrase. Use aspas apenas quando conhecer as palavras exatas; ao resumir uma ideia, indique o autor ou a obra sem aspas. Filme e música podem contribuir, desde que a cena ou o tema sejam explicados. Não transforme ficção em dado estatístico nem atribua números sem fonte.", example: "Em Quarto de despejo, Carolina Maria de Jesus relata a experiência da fome e da precariedade urbana. Essa perspectiva permite discutir como a exclusão material também reduz as condições de participação social.", exercise: "Escolha uma referência da biblioteca. Escreva duas frases: uma explica a obra e outra a liga à sua tese.", check: "Se eu retirar o nome do autor, ainda existe uma explicação específica?" },
  { title: "Construa coesão e clareza", summary: "Conectivos e retomadas precisam expressar relações reais.", lesson: "Use oposição para contrastar ideias, causa para explicar motivos e conclusão para derivar resultados. Evite encadear conectivos sem necessidade. Retome palavras com expressões precisas: ‘essa barreira’ deve apontar para uma barreira identificável. Revise concordância, pontuação e períodos excessivamente longos.", example: "A plataforma oferece atendimento remoto. Contudo, suas letras pequenas dificultam a leitura. Essa barreira visual reduz a autonomia de parte dos usuários. A última frase retoma uma dificuldade específica.", exercise: "Marque todos os conectivos do seu parágrafo e escreva sua função na margem. Corrija as relações incompatíveis.", check: "Cada pronome e expressão de retomada tem um referente claro?" },
  { title: "Elabore a intervenção", summary: "Agente, ação, meio, finalidade e detalhamento conectados ao diagnóstico.", lesson: "Escolha um agente capaz de executar a ação. Explique o que será feito, por qual meio e para qual resultado. Detalhe um elemento, por exemplo o público, a frequência ou o funcionamento. A proposta deve respeitar direitos humanos e responder ao que você desenvolveu, sem introduzir um problema novo.", example: "As secretarias municipais de educação, em parceria com bibliotecas públicas, podem oferecer oficinas gratuitas de uso de serviços digitais, por meio de encontros práticos semanais destinados a idosos, para ampliar sua autonomia no acesso a esses serviços.", exercise: "Sublinhe os cinco elementos no exemplo. Depois crie outra ação para a barreira de acessibilidade das plataformas.", check: "A ação é concreta e o agente tem condições de realizá-la?" },
  { title: "Revise pelas cinco competências", summary: "Confira linguagem, tema, argumentação, coesão e intervenção.", lesson: "Faça uma leitura para cada objetivo: C1, clareza e norma-padrão; C2, tema, tipo textual e repertório; C3, seleção e organização dos argumentos; C4, relações entre frases e parágrafos; C5, proposta de intervenção. Corrija primeiro desvios de tema e lacunas de raciocínio, depois escolhas de palavras.", example: "Antes: ‘A tecnologia é ruim e o governo deve resolver’. Depois: ‘Interfaces pouco acessíveis dificultam o uso de serviços por idosos; órgãos responsáveis devem testar a navegação com esse público e adequar seus sistemas’. A revisão torna problema e ação específicos.", exercise: "Anote uma melhoria prioritária por competência e reescreva apenas o parágrafo mais frágil.", check: "Consigo explicar o que melhorei e por que o texto ficou mais claro?" },
];

export const MIND_MAP = [
  { branch: "Tese", nodes: ["Inclusão digital de idosos", "Formação insuficiente + interfaces inacessíveis"] },
  { branch: "Argumento 1", nodes: ["Causa: falta de orientação", "Efeito: dependência de terceiros", "Repertório: educação e autonomia"] },
  { branch: "Argumento 2", nodes: ["Causa: barreiras de navegação", "Efeito: restrição de acesso a serviços", "Repertório: participação e cidadania"] },
  { branch: "Intervenção", nodes: ["Bibliotecas + oficinas práticas", "Órgãos responsáveis + testes de acessibilidade", "Finalidade: autonomia e acesso"] },
];

export const CONNECTOR_LESSONS = [
  ["Abrir argumento", ["Em primeiro plano", "Inicialmente", "Sob essa perspectiva", "Em uma primeira análise"], "Em primeiro plano, a falta de orientação dificulta o uso dos serviços.", "Apresente o argumento; evite anunciar uma ordem que não continuará no texto."],
  ["Adicionar", ["Além disso", "Ademais", "Somado a isso", "Também", "Ainda", "Não só… mas também"], "Além disso, o desenho das plataformas pode restringir o acesso.", "Acrescente uma ideia nova, sem repetir o argumento anterior."],
  ["Contrapor", ["Entretanto", "Contudo", "No entanto", "Todavia", "Em contrapartida", "Por outro lado"], "O serviço está disponível on-line. Contudo, parte do público não consegue utilizá-lo.", "A segunda ideia precisa contrastar com a primeira."],
  ["Conceder", ["Embora", "Ainda que", "Mesmo que", "Apesar de", "Se bem que"], "Embora o serviço seja gratuito, seu acesso exige conexão.", "Embora pede oração; apesar de pode introduzir nome ou infinitivo."],
  ["Explicar causa", ["Porque", "Uma vez que", "Visto que", "Já que", "Em razão de", "Devido a"], "O acesso fica restrito, uma vez que a conexão não chega a todas as áreas.", "Não confunda o motivo com a consequência."],
  ["Indicar consequência", ["Por isso", "Consequentemente", "Por conseguinte", "Assim", "Desse modo", "Dessa forma"], "As instruções são confusas. Por isso, usuários abandonam o atendimento.", "A consequência deve decorrer da ideia anterior."],
  ["Exemplificar", ["Por exemplo", "A exemplo de", "Como ilustração", "É o caso de"], "Serviços essenciais, a exemplo do agendamento de consultas, exigem navegação acessível.", "O exemplo ilustra; explique como ele sustenta o argumento."],
  ["Comparar", ["Da mesma forma", "De modo semelhante", "Assim como", "Analogamente"], "Assim como o espaço físico, o ambiente digital precisa considerar a acessibilidade.", "Explique a semelhança sem apagar diferenças importantes."],
  ["Estabelecer condição", ["Se", "Caso", "Desde que", "Contanto que"], "O atendimento será mais inclusivo se houver alternativas acessíveis.", "A condição não deve ser apresentada como fato já ocorrido."],
  ["Indicar finalidade", ["Para que", "A fim de", "Com o objetivo de", "Com a finalidade de"], "As bibliotecas podem oferecer oficinas a fim de ampliar a autonomia digital.", "Finalidade é o resultado pretendido, não uma garantia de sucesso."],
  ["Situar no tempo", ["Atualmente", "Ao longo do tempo", "Posteriormente", "Enquanto", "Antes de"], "Antes de ampliar o serviço, é necessário testar sua acessibilidade.", "Evite ‘atualmente’ com fatos de outro período."],
  ["Concluir e propor", ["Portanto", "Logo", "Diante disso", "Em síntese", "Em vista disso"], "Diante disso, cabe aos órgãos responsáveis simplificar a navegação dos serviços.", "Conclua a análise e conecte a proposta ao diagnóstico."],
] as const;

export const PRACTICE_THEMES = [
  { title: "Desafios para combater a desinformação científica no Brasil", axis: "Ciência e comunicação", reason: "Permite treinar confiança nas instituições, educação midiática e acesso ao conhecimento." },
  { title: "Caminhos para ampliar a inclusão digital da população idosa brasileira", axis: "Tecnologia e cidadania", reason: "Conecta acessibilidade, autonomia e transformação dos serviços." },
  { title: "A importância da preservação da memória cultural nas cidades brasileiras", axis: "Cultura", reason: "Articula patrimônio, participação comunitária e identidade." },
  { title: "Desafios para a adaptação das cidades brasileiras a eventos climáticos extremos", axis: "Meio ambiente", reason: "Possibilita discutir planejamento urbano e desigualdade na proteção da população." },
  { title: "Caminhos para promover a educação midiática nas escolas brasileiras", axis: "Educação", reason: "Relaciona interpretação crítica, circulação de informações e formação cidadã." },
  { title: "Barreiras à inclusão de pessoas com deficiência no mundo do trabalho", axis: "Inclusão", reason: "Permite analisar acessibilidade, formação e discriminação." },
  { title: "Desafios para reduzir a insegurança alimentar no Brasil", axis: "Direitos sociais", reason: "Articula renda, abastecimento e acesso a direitos." },
  { title: "Caminhos para valorizar a ciência produzida no Brasil", axis: "Ciência", reason: "Permite explorar divulgação científica e relações entre pesquisa e sociedade." },
  { title: "Desafios para combater a solidão e fortalecer vínculos comunitários", axis: "Convivência", reason: "Abre discussão sobre espaços públicos, redes de apoio e participação." },
  { title: "A promoção do acesso à leitura em territórios periféricos", axis: "Educação e cultura", reason: "Relaciona bibliotecas, mediação de leitura e desigualdade territorial." },
  { title: "Desafios para assegurar o uso responsável da inteligência artificial na educação", axis: "Tecnologia", reason: "Exercita autoria, acesso desigual e formação crítica." },
  { title: "Caminhos para ampliar o acesso ao saneamento básico no Brasil", axis: "Cidadania", reason: "Conecta infraestrutura, desigualdade territorial e qualidade de vida." },
];
